# Generated by Django 5.1.2 on 2024-11-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_cose_este_tel_este_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='este',
            name='birthday',
            field=models.DateField(),
        ),
    ]
