# Generated by Django 5.1.2 on 2024-12-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_este_birthday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Este',
            new_name='Este_User',
        ),
    ]
