# Generated by Django 5.1.2 on 2024-12-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_este_este_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Este_Course_Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cose_name', models.TextField()),
                ('contents', models.TextField()),
                ('price', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
