# Generated by Django 5.1.2 on 2024-12-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_este_course_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='este_course_contents',
            name='treatment_area',
            field=models.TextField(default='Default Area'),
        ),
    ]
